# This yaml creates the prerequsite secrets, service account and PVC for the Aqua components. It is written as a pre-install hook.
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-admin-password
  annotations:
    "helm.sh/hook": pre-install
  labels:
    secretType: aquaSecurity
type: Opaque
data:
  password: {{ b64enc (.Values.global.aquaPassword) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-database-password
  annotations:
    "helm.sh/hook": pre-install
  labels:
    secretType: aquaSecurity
type: Opaque
data:
{{ if .Values.global.dbExternalServiceHost }}
  password: {{ b64enc (.Values.global.dbExternalPassword) }}
{{ else }}
  password: {{ b64enc (.Values.global.dbPassword) }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-enforcer-token
  annotations:
    "helm.sh/hook": pre-install
  labels:
    secretType: aquaSecurity
type: Opaque
data:
  token: {{ b64enc (randAlphaNum 32) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-database-pvc
  annotations:
    "helm.sh/hook": pre-install
spec:
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi