---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-enforcer
  labels:
    app: {{ .Release.Name }}-enforcer
    component: {{ .Release.Name }}-enforcer
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-enforcer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-enforcer
      name: {{ .Release.Name }}-enforcer
    spec:
      hostPID: true
      containers:
      - name: enforcer
        image: "{{.Values.image}}"
        securityContext:
          privileged: true
        imagePullPolicy: "{{.Values.imagePullPolicy}}"
        env:
          - name: AQUA_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-enforcer-token
                key: password
          - name: AQUA_SERVER
            value: {{ .Release.Name }}-gateway-svc:8443
          - name: AQUA_LOGICAL_NAME
            value: {{ .Release.Name }}-gke
          - name: RESTART_CONTAINERS
            value: "no"
          - name: AQUA_INSTALL_PATH
            value: /var/lib/aquasec
        volumeMounts:
          - mountPath: /var/run
            name: var-run
          - mountPath: /dev
            name: dev
          - mountPath: /host/sys
            name: sys
            readOnly: true
          - mountPath: /host/proc
            name: proc
            readOnly: true
          - mountPath: /host/etc
            name: etc
            readOnly: true
          - mountPath: /host/opt/aquasec
            name: aquasec
            readOnly: true
          - mountPath: /opt/aquasec/tmp
            name: aquasec-tmp
          - mountPath: /opt/aquasec/audit
            name: aquasec-audit
      volumes:
        - name: var-run
          hostPath:
            path: /var/run
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: proc
          hostPath:
            path: /proc
        - name: etc
          hostPath:
            path: /etc
        - name: aquasec
          hostPath:
            path: /var/lib/aquasec
        - name: aquasec-tmp
          hostPath:
            path: /var/lib/aquasec/tmp
        - name: aquasec-audit
          hostPath:
            path: /var/lib/aquasec/audit

