apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: {{ .Release.Name }}-gateway
    component: {{ .Release.Name }}-gateway
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.gate.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-gateway
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-gateway
      name: {{ .Release.Name }}-gateway
    spec:
      containers:
      - name: gate
        image: "{{ .Values.image }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        env:
          - name: AQUA_CONSOLE_SECURE_ADDRESS
            value: {{ .Release.Name }}-console-svc:443
          - name: SCALOCK_GATEWAY_PUBLIC_IP
            value: {{ .Release.Name }}-gateway-svc
          - name: SCALOCK_DBUSER
            value: "postgres"
          {{- if .Values.ExternalDBenabled }}
          - name: SCALOCK_DBPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.ExternalDBPassword }}
                key: password
          {{- else }}
          - name: SCALOCK_DBPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-secret
                key: password
          {{- end }}
          - name: SCALOCK_DBNAME
            value: "scalock"
          - name: SCALOCK_DBHOST
            {{ if .Values.ExternalDBenabled }}
            value: {{ .Values.ExternalDBHost }}
            {{ else }}
            value: {{ .Release.Name }}-database-svc
            {{ end }}
          - name: SCALOCK_DBPORT
            value: {{ default 5432 .Values.DBServicePort | quote }}
          - name: SCALOCK_AUDIT_DBUSER
            value: "postgres"
          {{- if .Values.ExternalDBenabled }}
          - name: SCALOCK_AUDIT_DBPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.ExternalDBPassword }}
                key: password
          {{- else }}
          - name: SCALOCK_AUDIT_DBPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name  }}-db-secret
                key: password
          {{ end }}
          - name: SCALOCK_AUDIT_DBNAME
            value: "slk_audit"
          - name: SCALOCK_AUDIT_DBHOST
            {{ if .Values.ExternalDBenabled }}
            value: {{ .Values.ExternalDBHost }}
            {{ else }}
            value: {{ .Release.Name }}-database-svc
            {{ end }}
          - name: SCALOCK_AUDIT_DBPORT
            value: {{ default 5432 .Values.DBServicePort | quote }}
          {{- if .Values.ssl }}
          - name: SCALOCK_DBSSL
            value: require
          {{- end }}
          {{- if .Values.ssl }}
        - name: SCALOCK_AUDIT_DBSSL
          value: require
          {{- end }}
        ports:
        - containerPort: 3622
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
