apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-svc
  labels:
    app: {{ .Release.Name }}-gateway
    component: {{ .Release.Name }}-gateway
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"      
spec:
  type: ClusterIP
  ports:
    - name: aqua-gate
      port: 3622
      targetPort: 3622
      protocol: TCP
    - name: aqua-gate-ssl
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-gateway
