---
{{ if .Values.global.ExternalDBHost }}
{{ else }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: {{ .Release.Name }}-database
    component: {{ .Release.Name }}-database
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-database
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-database
      name: {{ .Release.Name }}-database
    spec:
      serviceAccount: aqua-sa
      containers:
      - name: db
        image: "{{ .Values.global.imageCredentials.registry }}/marketplace-database:{{ .Values.global.imageTag }}"
        imagePullPolicy: {{.Values.global.imagePullPolicy}}
        env:
          - name: PGDATA
            value: "/var/lib/postgresql/data/db-files"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{.Release.Name}}-database-password
                key: password
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: "{{ .Release.Name }}-database-vol"
      volumes:
        - name: "{{ .Release.Name }}-database-vol"
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-database-pvc"
{{ end }}
